import React, { useMemo } from 'react';
import { ScrollView, StyleSheet, Text, View, Platform } from 'react-native';
import { StatusBar } from 'expo-status-bar';

// Bundled assets: generated by running the SemanticChunker script
// eslint-disable-next-line @typescript-eslint/no-var-requires
const docData: { text: string; filename: string } = require('./assets/document.json');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const chunksData: { chunks: Chunk[]; total: number } = require('./assets/chunks.json');

// ─── Types ────────────────────────────────────────────────────────────────────

type Chunk = {
  index: number;
  start: number;
  end: number;
  text: string;
};

type Segment = {
  text: string;
  /** null means the text lies between chunks (no highlight) */
  chunkIndex: number | null;
};

// ─── Palette (20 distinct pastels, cycles if > 20 chunks) ────────────────────

const PALETTE = [
  '#FFCDD2', '#FFE0B2', '#FFF9C4', '#DCEDC8', '#C8E6C9',
  '#B2EBF2', '#B3E5FC', '#BBDEFB', '#C5CAE9', '#D1C4E9',
  '#E1BEE7', '#F8BBD0', '#D7CCC8', '#CFD8DC', '#B2DFDB',
  '#F0F4C3', '#FFD54F', '#A5D6A7', '#80DEEA', '#CE93D8',
];

function chunkColor(index: number): string {
  return PALETTE[index % PALETTE.length];
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function buildSegments(fullText: string, chunks: Chunk[]): Segment[] {
  const sorted = [...chunks].sort((a, b) => a.start - b.start);
  const segments: Segment[] = [];
  let cursor = 0;

  for (const chunk of sorted) {
    if (chunk.start > cursor) {
      segments.push({ text: fullText.slice(cursor, chunk.start), chunkIndex: null });
    }
    if (chunk.end > chunk.start) {
      segments.push({ text: fullText.slice(chunk.start, chunk.end), chunkIndex: chunk.index });
    }
    cursor = Math.max(cursor, chunk.end);
  }

  if (cursor < fullText.length) {
    segments.push({ text: fullText.slice(cursor), chunkIndex: null });
  }

  return segments;
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function CompareChunks() {
  const { text, filename } = docData;
  const { chunks, total } = chunksData;

  const segments = useMemo(() => buildSegments(text, chunks), [text, chunks]);

  return (
    <View style={styles.root}>
      <StatusBar style="dark" />

      {/* ── Top bar ── */}
      <View style={styles.topBar}>
        <Text style={styles.topTitle}>Semantic Chunk Viewer</Text>
        <Text style={styles.topSub}>
          {total} chunks · all-MiniLM-L6-v2 · threshold 0.8 · chunk_size 1200
        </Text>
      </View>

      {/* ── Legend (horizontal scroll) ── */}
      <ScrollView
        horizontal
        style={styles.legendBar}
        contentContainerStyle={styles.legendContent}
        showsHorizontalScrollIndicator={false}
      >
        {chunks.map((_, i) => (
          <View key={i} style={[styles.legendChip, { backgroundColor: chunkColor(i) }]}>
            <Text style={styles.legendChipText}>Chunk {i + 1}</Text>
          </View>
        ))}
      </ScrollView>

      {/* ── PDF page area ── */}
      <ScrollView
        style={styles.pageArea}
        contentContainerStyle={styles.pageAreaContent}
        showsVerticalScrollIndicator
      >
        {/* Paper */}
        <View style={styles.paper}>
          {/* Fake PDF header row */}
          <View style={styles.pdfHeader}>
            <View style={styles.pdfHeaderLine} />
            <Text style={styles.pdfFilename} numberOfLines={1}>{filename}</Text>
            <View style={styles.pdfHeaderLine} />
          </View>

          {/* Body text with inline chunk highlights */}
          <Text style={styles.bodyText}>
            {segments.map((seg: Segment, i: number) =>
              seg.chunkIndex !== null ? (
                <Text
                  key={i}
                  style={[
                    styles.bodyText,
                    styles.chunkHighlight,
                    { backgroundColor: chunkColor(seg.chunkIndex) },
                  ]}
                >
                  {seg.text}
                </Text>
              ) : (
                <Text key={i} style={styles.bodyText}>
                  {seg.text}
                </Text>
              )
            )}
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const IS_WEB = Platform.OS === 'web';

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#E8EAED',
  },

  // Top bar
  topBar: {
    backgroundColor: '#1A1A2E',
    paddingTop: IS_WEB ? 20 : 48,
    paddingBottom: 12,
    paddingHorizontal: 20,
  },
  topTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  topSub: {
    color: '#A0A8C0',
    fontSize: 12,
    marginTop: 4,
  },

  // Legend
  legendBar: {
    maxHeight: 44,
    backgroundColor: '#F5F5F5',
    borderBottomWidth: 1,
    borderBottomColor: '#DADADA',
  },
  legendContent: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 6,
    flexDirection: 'row',
    alignItems: 'center',
  },
  legendChip: {
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginRight: 6,
  },
  legendChipText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#333',
  },

  // Page area (the grey "viewer" background)
  pageArea: {
    flex: 1,
  },
  pageAreaContent: {
    paddingVertical: 32,
    paddingHorizontal: 20,
    alignItems: 'center',
  },

  // White paper
  paper: {
    width: '100%',
    maxWidth: 760,
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
    paddingHorizontal: 56,
    paddingVertical: 60,
    // Shadow
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.18,
        shadowRadius: 12,
      },
      android: {
        elevation: 8,
      },
      web: {
        // @ts-ignore web-only
        boxShadow: '0 4px 20px rgba(0,0,0,0.18)',
      },
    }),
  },

  // Fake PDF top bar inside the paper
  pdfHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 28,
    gap: 10,
  },
  pdfHeaderLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#C0C0C0',
  },
  pdfFilename: {
    fontSize: 10,
    color: '#888',
    letterSpacing: 0.3,
    fontFamily: Platform.select({ ios: 'Courier', android: 'monospace', default: 'monospace' }),
    flexShrink: 1,
  },

  // Body text
  bodyText: {
    fontSize: 14,
    lineHeight: 24,
    color: '#1A1A1A',
    fontFamily: Platform.select({
      ios: 'Georgia',
      android: 'serif',
      default: 'Georgia, "Times New Roman", serif',
    }),
    textAlign: 'left',
  },

  // Highlighted chunk span
  chunkHighlight: {
    borderRadius: 2,
  },
});
