yaml_config_files: ['r1_config.yaml', 'r2_config.yaml']
llm_models: ['llama-3.1-8b-instant', 'openai/gpt-oss-120b']
embedding_models: ['BAAI/bge-small-en-v1.5', 'BAAI/bge-small-en-v1.5']
embedding_model_settings:
  - name: BAAI/bge-small-en-v1.5
    settings:
      embedding_dim: 384
retriever_settings:
  - name: r1
    retriever_params:
      top_k: 1
      alpha: 0.6
  - name: r2
    retriever_params:
      top_k: 1
      alpha: 0.9
output_files: ['./output/r1.json', './output/r2.json']
eval_rq_output: ['./output/eval_results/r1_rq.xlsx', './output/eval_results/r2_rq.xlsx']
eval_aq_output: ['./output/eval_results/r1_aq.xlsx', './output/eval_results/r2_aq.xlsx']
eval_all_output: ['./output/eval_results/r1_all.xlsx', './output/eval_results/r2_all.xlsx']